library(riskParityPortfolio)
library(xts)
library(quantmod)
library(PerformanceAnalytics)

N <- 30
Sigma <- diag((1:N) ^ 2)
Sigma[1, 2] <- 10

w_diag <- 1/sqrt(diag(Sigma))
w_diag <- w_diag/sum(w_diag)

start <- Sys.time()
res <- riskParityPortfolioGenSolver(Sigma)
end <- Sys.time()
print(end - start)
#start <- Sys.time()
#res_cvx <- riskParityPortfolioCVX(Sigma)
#end <- Sys.time()
#print(end - start)
start <- Sys.time()
res_qp <- riskParityPortfolioQP(Sigma)
end <- Sys.time()
print(end - start)
cat(res$init_portfolio_weights, '\n')
cat(res$portfolio_weights, '\n')
#cat(res_cvx$portfolio_weights, '\n')
cat(w_diag, '\n')
cat(sum(res$portfolio_weights))
cat(sum(res_qp$portfolio_weights))
barplot(t(res$portfolio_weights))
barplot(t(res$risk_contributions))
#barplot(t(res_cvx$portfolio_weights))
#barplot(t(res_cvx$risk_contributions))
barplot(t(res_qp$portfolio_weights))
barplot(t(res_qp$risk_contributions))
barplot(t(w_diag))
barplot(t(w_diag * (Sigma %*% w_diag)))
Niter <- length(res_qp$obj_fun)
plot(c(1:Niter), res_qp$obj_fun)

