# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
A_rc_double_index <- function(w, Sigma, N) {
    .Call('_riskParityPortfolio_A_rc_double_index', PACKAGE = 'riskParityPortfolio', w, Sigma, N)
}

