# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

risk_parity_portfolio_ccd_spinu <- function(Sigma, b, tol, maxiter) {
    .Call('_riskParityPortfolio_risk_parity_portfolio_ccd_spinu', PACKAGE = 'riskParityPortfolio', Sigma, b, tol, maxiter)
}

risk_parity_portfolio_ccd_roncalli <- function(Sigma, b, tol, maxiter) {
    .Call('_riskParityPortfolio_risk_parity_portfolio_ccd_roncalli', PACKAGE = 'riskParityPortfolio', Sigma, b, tol, maxiter)
}

active_risk_parity_portfolio_ccd <- function(Sigma, b, mu, c, r, tol, maxiter) {
    .Call('_riskParityPortfolio_active_risk_parity_portfolio_ccd', PACKAGE = 'riskParityPortfolio', Sigma, b, mu, c, r, tol, maxiter)
}

risk_parity_portfolio_nn <- function(Sigma, b, tol, maxiter) {
    .Call('_riskParityPortfolio_risk_parity_portfolio_nn', PACKAGE = 'riskParityPortfolio', Sigma, b, tol, maxiter)
}

obj_function_spinu <- function(Sigma, x, b) {
    .Call('_riskParityPortfolio_obj_function_spinu', PACKAGE = 'riskParityPortfolio', Sigma, x, b)
}

obj_function_roncalli <- function(Sigma, x, b) {
    .Call('_riskParityPortfolio_obj_function_roncalli', PACKAGE = 'riskParityPortfolio', Sigma, x, b)
}

